### PR TITLE
Mark the `project_name` field unique.

### PR DESCRIPTION
**Pull request by gz**
This means we can reasonably hide the project ID from the user.

### CODE REVIEW

**Review by gz — COMMENTED** [review]
Also need to update error handling in https://github.com/vmware/database-stream-processor/pull/311/files#diff-d5b4d76084ac8d75b29640302d2a38081a6553508bc303210aeecb175da60856R300

**Review by ryzhyk — CHANGES_REQUESTED** [review]
- We need to make sure that `new_project` returns a meaningful error message too.  It's often the first API call the client performs, which means that it may fail for more than one reason (e.g., old schema).  So we need to either distinguish the uniqueness violation SQlite error or check if the name exists as a separate query.
- This will also break workflows where project name doesn't matter and is left blank, e.g., because the client creates a project and uses it via an API handle. I guess this should be solved on the client side by either getting a list of projects and generating new unique names, e.g., "Project 5", or generating probabilistically unique names a la UUIDs.

**Comment by gz** [comment]
I fixed the error handling; still need to look into the python API to generate a unique name by default.

**Comment by ryzhyk** [comment]
> I fixed the error handling; still need to look into the python API to generate a unique name by default.

I don't think we need that now.  You upset the formatter though :)

**Review by ryzhyk — APPROVED** [review]

**Comment by gz** [comment]
> > I fixed the error handling; still need to look into the python API to generate a unique name by default.
> 
> I don't think we need that now. You upset the formatter though :)

Fixed, for some reason I need to use the nightly version for cargo fmt :/

**Pull request merged**
